name: ecommerce-api
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - flask==2.0.1
    - flask-sqlalchemy==2.5.1
    - psycopg2-binary==2.9.1
    - pyjwt==2.1.0
    - python-dotenv==0.19.0
    - werkzeug==2.0.1
    - sqlalchemy==1.4.23
    - pytest==6.2.5
    - requests==2.26.0
    - bcrypt==3.2.0
    - email-validator==1.1.3
    - flask-cors==3.0.10 